stages:
  
  download_dataset:
    cmd: sh ./datasets/download_pix2pix_dataset.sh facades
    deps:
      - datasets/download_pix2pix_dataset.sh
    outs: 
      - datasets/facades/
  
  download_weights:
    cmd: sh ./scripts/download_pix2pix_model.sh facades_label2photo
    deps:
      - scripts/download_pix2pix_model.sh
    outs:
      - checkpoints/facades_label2photo_pretrained/latest_net_G.pth

  write_env:
    cmd: python write_env.py
    deps:
      - params.yaml
      - write_env.py
    outs:
      - .env

  train:
    cmd: source .env && python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --n_epochs $n_epochs --save_epoch_freq $n_epochs --n_epochs_decay $n_epochs_decay --gpu_ids -1
    deps:
      - .env
      - datasets/facades/
      - checkpoints/facades_label2photo_pretrained/latest_net_G.pth
    params:
      - n_epochs
      - n_epochs_decay
    outs:
      - checkpoints/facades_pix2pix

  # test:
  #   cmd: python test.py --dataroot ./datasets/facades --model pix2pix --name facades_pix2pix --gpu_ids -1
  #   deps:
  #     - checkpoints/facades_pix2pix
  #   outs:
  #     - results/facades_pix2pix/