stages:
  
  download_dataset:
    cmd: sh ./datasets/download_pix2pix_dataset.sh ${dataset}
    deps:
      - datasets/download_pix2pix_dataset.sh
    outs: 
      - datasets/${dataset}/

  train:
    cmd: >-
      python train.py
      --model pix2pix
      --dataroot ./datasets/${dataset}
      --name ${dataset}_pix2pix
      --n_epochs ${n_epochs}
      --n_epochs_decay ${n_epochs_decay}
      --netG ${netG}
      --direction BtoA
      --gpu_ids 0
    deps:
      - datasets/${dataset}/
    params:
      - n_epochs
      - n_epochs_decay
      - dataset
      - netG
    outs:
      - checkpoints/${dataset}_pix2pix

  test:
    cmd: >-
      python test.py
      --model pix2pix
      --dataroot ./datasets/${dataset}
      --name ${dataset}_pix2pix
      --direction BtoA
      --gpu_ids 0
    deps:
      - checkpoints/${dataset}_pix2pix
    outs:
      - results/${dataset}_pix2pix/

  plot:
    cmd: python write_plots.py checkpoints/${dataset}_pix2pix/loss_log.txt ${dataset}
    deps:
      - checkpoints/${dataset}_pix2pix/loss_log.txt
      - write_plots.py
    plots:
      - ${dataset}_loss.csv:
          cache: false